### ISSUE TITLE
Thanks for publishing this!

### ISSUE THREAD

**Issue by sagarsoni7** [timfish/webpack-asset-relocator-loader#1] opened 2021-06-14 06:48 UTC
I had a hard time using `@marshallofsound/webpack-asset-relocator-loader` with webpack 5.
Tried Vercel loader but that too doesn't work with Electron-forge out of box.

Everything's working as expected after installing this module.

Thanks @timfish

**Comment by timfish** [comment] 2021-06-14 10:19
This functionality will eventually make it into forge so you'll be able to use the plain vercel loader. This module is just a stopgap solution until I find time to finish this PR with some suitable tests!
https://github.com/electron-userland/electron-forge/pull/2320

**Comment by ngiafeno** [comment] 2021-06-16 12:14
@timfish Thanks for publishing this, 
Does anybody now how to check if the relocator really work because I still encounter the error  "No native build was found ..." in prod. And I don't know if it is an issue in the the library I use or in my project config. Thank you for your help
PS: ref-napi is the lib

**Comment by sagarsoni7** [comment] 2021-06-16 12:23
@ngiafeno - Did you try this? 

https://github.com/vercel/pkg/issues/912

**Comment by timfish** [comment] 2021-06-16 12:36
I could just be that `@vercel/webpack-asset-relocator-loader` doesn't fully work with `ref-napi`.

If you link to a repository reproducing the issue I can probably confirm why.

**Comment by ngiafeno** [comment] 2021-06-16 14:03
> @ngiafeno - Did you try this?
> 
> [vercel/pkg#912](https://github.com/vercel/pkg/issues/912)

Thank you but this doesn't work for me

**Comment by ngiafeno** [comment] 2021-06-17 12:23
> I could just be that `@vercel/webpack-asset-relocator-loader` doesn't fully work with `ref-napi`.
> 
> If you link to a repository reproducing the issue I can probably confirm why.

@timfish this  [repository](https://github.com/ngiafeno/sample-electron-native-modules)reproduces the error, 
I actually work on
 windows 10 
node version 14.17.0
Thank you

**Comment by timfish** [comment] 2021-06-17 12:55
The Vercel loader doesn't appear to support the patterns used by `ref-napi` (ie. `node-gyp-build`) so asset relocation wont work.

I would instead try using [this forge plugin](https://www.npmjs.com/package/@timfish/forge-externals-plugin) that I created. 

I would also recommend that you do not proxy native calls through Electron IPC like that. I would instead load the native module in `preload` and expose the functionality via `contextBridge`. This would mean that you don't have the overhead of IPC. The main process should only really be used for opening/closing/controlling windows or accessing Electron functionality that is only available in the main process.

**Comment by ngiafeno** [comment] 2021-06-18 07:54
Thanks for your help, the library you provided solved my issue relative to native modules.

**Closed as completed** 2021-06-24 16:27 UTC

**Comment by ngiafeno** [comment] 2021-06-27 16:49
@timfish, following your recommendation, I actually load my native function on preload and exposed it though contextBrige, And now i'm getting stuck by this error: 
```unable to load preload script
No native build was found for platform=win32 arch=x64 runtime=electron abi=89 uv=1 libc=glibc node=14.16.0 electron=13.0.1 webpack=true loaded from: C:\Users\user\project\.webpack\renderer
```
I don't know where I'm doing wrong.
I put my code on that branch
https://github.com/ngiafeno/sample-electron-native-modules/blob/using-preload/src/rendererPreload.ts 
Thank you

**Comment by timfish** [comment] 2021-06-27 16:51
@ngiafeno if the loader doesn't work, remove it and use this plugin:
https://www.npmjs.com/package/@timfish/forge-externals-plugin

**Comment by ngiafeno** [comment] 2021-06-27 17:00
I already use it on this project, thanks to that library I was able to load  natives modules when I loaded them on the main process. Or is ther any way to specify that a module is being  loader from the preload?

**Comment by timfish** [comment] 2021-06-28 12:06
@ngiafeno when using `@timfish/forge-externals-plugin` you need to add your native modules to webpack config `externals` for whichever process is relevant to you. ie. if you want it to be external from the preload or renderer, you need to add it to [here](https://github.com/ngiafeno/sample-electron-native-modules/blob/using-preload/webpack.renderer.config.js) too.

**Comment by ngiafeno** [comment] 2021-06-28 12:16
Thank you @timfish, You always save me with my lack of understanding electron

**Comment by muhajirdev** [comment] 2021-07-09 10:07
Thanks for publishing this!
